// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWVHgqCv9Xgr2a6GNyp70a44OXGYrJAq8',
    appId: '1:289073996076:web:9db5ab5a21c04834378c89',
    messagingSenderId: '289073996076',
    projectId: 'fir-44aae',
    authDomain: 'fir-44aae.firebaseapp.com',
    storageBucket: 'fir-44aae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAc9rK2Fxt7RTci-AAFTEeWU-Eus3ebsM',
    appId: '1:289073996076:android:0bd5bcae625e71b3378c89',
    messagingSenderId: '289073996076',
    projectId: 'fir-44aae',
    storageBucket: 'fir-44aae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEIDGGK9ZJccQTN5mErwvbynrO_M3ND2w',
    appId: '1:289073996076:ios:5f334ec5b83c0694378c89',
    messagingSenderId: '289073996076',
    projectId: 'fir-44aae',
    storageBucket: 'fir-44aae.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEIDGGK9ZJccQTN5mErwvbynrO_M3ND2w',
    appId: '1:289073996076:ios:5f334ec5b83c0694378c89',
    messagingSenderId: '289073996076',
    projectId: 'fir-44aae',
    storageBucket: 'fir-44aae.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWVHgqCv9Xgr2a6GNyp70a44OXGYrJAq8',
    appId: '1:289073996076:web:9979f2e4f7ca9ef7378c89',
    messagingSenderId: '289073996076',
    projectId: 'fir-44aae',
    authDomain: 'fir-44aae.firebaseapp.com',
    storageBucket: 'fir-44aae.appspot.com',
  );
}
